### ISSUE TITLE
Newest version not on jcenter nor on mavenCentral

### ISSUE THREAD

**Issue by andretietz** [TheBoegl/gradle-launch4j#101]
Hey, I just wanted to use the plugin and figured out that the last available version is 2.4.6 on jcenter.
According to the [releases page on github](https://github.com/TheBoegl/gradle-launch4j/releases) it should be 2.4.8
One of those should be reachable:
mavenCentral:
https://repo.maven.apache.org/maven2/edu/sc/seis/gradle/launch4j/2.4.8/launch4j-2.4.8.pom
jcenter:
https://jcenter.bintray.com/edu/sc/seis/gradle/launch4j/2.4.8/launch4j-2.4.8.pom

Hint: I know that releasing versions to mavenCentral can be a pain.
I can recommend: https://github.com/vanniktech/gradle-maven-publish-plugin in combination with github actions in order to automate releases.

**Comment by jpstotz** [comment]
For version 2.5.0 is now the same situation. Therefore the example configuration presented in the project readme e.g. for gradle using `id 'edu.sc.seis.launch4j' version '2.5.0'` does not work. 

According to [Mavenrepository.com](https://mvnrepository.com/artifact/edu.sc.seis.launch4j/launch4j) the latest version in the "Gradle Plugins" repos is 2.4.9. 

Or does releasing a plugin in the Gradle Plugins repository just requires several days before it is if finally shown to the public?

**Comment by TheBoegl** [comment]
Snapshot releases currently don't work and I didn't find a way to fix it, when this issue was created. Version 2.5 will be released to gradle plugins when #106 is resolved and merged to main. Keep in mind the branching model (develop vs main)

**Comment by jpstotz** [comment]
@TheBoegl The it is a mistake that the default branch for the Git project is set to the `develop` branch? 

Because of this the Readme.md shown when you open https://github.com/TheBoegl/gradle-launch4j can be read as if v2.5.0 had already been released.

**Comment by TheBoegl** [comment]
@jpstotz I've added a badge for the current published version on the gradle plugins portal to help clarify which version can be simply used without checking the default branch.
AFAIK there is no option in GitHub to set a default view branch and a different default merge branch.
