### ISSUE TITLE
Verify min and max JRE versions with java 11

### ISSUE THREAD

**Issue by TheBoegl** [TheBoegl/gradle-launch4j#106]
Before releasing 2.5, we'll have to verify that the min and max jre versions work as expected for running the created exe with java 9 and later.

**Comment by jpstotz** [comment]
@TheBoegl Can you please elaborate a bit more what do you expect for performing this task?

From my perspective gradle-launch4j works as expected if the configuration file it generates contains the correct entries for specifying min and max jre version. Everything else is up to launch4j, which means if it does not work it is a bug of launch4j.
