### ISSUE TITLE
Remove deprecations

### ISSUE THREAD

**Issue by TheBoegl** [TheBoegl/gradle-launch4j#107]
Remove all deprecations for the next version

**Comment by nightm4re94** [comment]
Does this include the [deprecation of the JCenter repository](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)? Do you have any plans on retrieving dependencies from Maven Central instead?

**Comment by TheBoegl** [comment]
Sounds like a good idea!
