### ISSUE TITLE
Property jar is ignored in v2.5.0

### ISSUE THREAD

**Issue by maikelsteneker** [TheBoegl/gradle-launch4j#109]
See my example repository at https://github.com/maikelsteneker/gradle-launch4j-mwe.

This is an issue I discovered when upgrading from v2.4.9 to v2.5.0.

I'm creating a jar file without an extension (unusual, I know).

I'm using the following to set the jar that is to be used for launch4j:
```
tasks.withType<DefaultLaunch4jTask> {
    jar = "TICS"
}
```

Using `./gradlew createExe -Pl4j-debug`, I inspect the XML that's generated. For v2.4.9, the jar property is set as I expect it:
`  <jar>TICS</jar>`
After upgrading to v2.5.0, this property seems to be ignored:
`  <jar>TICS</jar>`

I'm aware that this property is deprecated and I should be using `jarTask` instead, but it would be good to preserve this functionality for backwards compatibility purposes. Alternatively, if this is not a valid use case, an error message would be helpful.

**Comment by TheBoegl** [comment]
This should be fixed on the next release with @naftalmm commit in e9924880

**Comment by TheBoegl** [comment]
fixed in #111
