### ISSUE TITLE
Change launch4j version to 3.5

### ISSUE THREAD

**Issue by Ceikry** [TheBoegl/gradle-launch4j#114]
The latest versions of launch4j have an issue where .exe files produced by it have headers that get the file flagged as a virus by many popular antiviruses. 

See: https://stackoverflow.com/questions/34592100/launch4j-compiled-java-application-executable-being-blocked-by-antivirus

And: https://sourceforge.net/p/launch4j/discussion/332683/thread/d5baedac/#6abf

**Comment by TheBoegl** [comment]
Launch4j 3.5 is quite dated, as are the threads you've linked. Is this really an issue with 3.14?
To further investigate this please provide an example project that does not work as expected.

**Comment by TheBoegl** [comment]
I'm closing this as no further feedback has been provided.
