### ISSUE TITLE
Build for Linux OS

### ISSUE THREAD

**Issue by Illusivebyte** [TheBoegl/gradle-launch4j#129]
I just discovered this tools and I was wondering if it is possible to configure the plugin to generate an executable for a specific OS. I am currently running in a linux dev environment but the executable that is generated is for windows. Is is even possible to generate a linux ELF file using this plugin? I did not see anything on doing this in the documentation (although I may have missed it.)

**Comment by TheBoegl** [comment]
This plugin only configures [launch4j](https://launch4j.sourceforge.net/) and, thus, only creates executable files for Windows.

With  jlink (JEP 282) and jpackage (JEP 392) you should be able to create the minimal required jre and package it according to your requirements better than with launch4j.
