### ISSUE TITLE
Created EXE needs admin-privileges to be run

### ISSUE THREAD

**Issue by brainbytes42** [TheBoegl/gradle-launch4j#134]
Hi,

thanks for this great plugin! (I'm using using version 2.5.4)

I'm using it to create a windows executable from a fat-jar, which works great for one project.

For another project, with the same settings,  I have not been able to create an EXE that would not need admin-privileges to run (which is not required for the first project mentioned). How does this happen? I need users without admin-role to be able to execute it...

Thanks for any suggestions!

**Comment by TheBoegl** [comment]
This plugin only invokes launch4j by trying to create the same configuration. Please try to create the Windows executable manually with launch4j version 3.14 and post any error messages or stacktraces you receive. To simplify the test you can use the `-Pl4j-debug` switch to generate the xml for launch4j.

I'll be alot easier if you can provide a link to your failing repo or a reproducable example.

**Comment by TheBoegl** [comment]
I'm closing this as there is no reply from @brainbytes42.
