### ISSUE TITLE
Question: Differences between 2.5.4 and 3.0.+ versions?

### ISSUE THREAD

**Issue by makiam** [TheBoegl/gradle-launch4j#158]
Hello.
I found some unexpected behavior change once I update plugin version from 2.5.4 to 3.0.0
In my project I create application exe file and copy it under application bin folder at distribution. 
Once I update plugin version created executable is created but no more copied to expected destination

See https://github.com/makiam/Tokonga/blob/main/ArtOfIllusion/build.gradle

Thanks in advance

**Comment by TheBoegl** [comment]
We migrated to gradle properties and removed the `launch4j` task, which was deprecated in version 2.0. Try using `createExe` instead when configuring the distribution.

**Comment by makiam** [comment]
Replacing original
`from("$buildDir/${launch4j.outputDir}/${launch4j.outfile}") { into("bin") }`
with
`from("$buildDir/${createExe.outputDir.get()}/${createExe.outfile.get()}") { into("bin") }`
solves an issue
Thanks

**Comment by TheBoegl** [comment]
@makiam does that answer your question and can we close this issue?

**Comment by makiam** [comment]
Sure. yes
