### ISSUE TITLE
documentation: not clear how include dependencies in .exe file

### ISSUE THREAD

**Issue by petrukhnov** [TheBoegl/gradle-launch4j#16]

**Comment by TheBoegl** [comment]
@petrukhnov Could you please elaborate on your issue description.

**Comment by petrukhnov** [comment]
E.g. I want to include all libs into .exe, so it will result in single file. Now it creates exe file and folder with libs.

Anyway I ended up with next config:
```gradle
launch4j {
    mainClassName = project.mainClassName
}

jar {
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    manifest {
        attributes(
                'Implementation-Version': project.version,
                'Main-Class': project.mainClassName)
    }
}
```

**Comment by TheBoegl** [comment]
Launch4j were not designed for that purpose. Though you could use a fat-jar mechanism containing your libraries. An example configuration is given in #6.
