### ISSUE TITLE
launch4j does not regard configured repositories

### ISSUE THREAD

**Issue by janosch24** [TheBoegl/gradle-launch4j#171]
In my *settins.gradle* I configured some repositories to find locally hosted dependencies:
```
// == Define locations for dependencies ==
dependencyResolutionManagement {
    repositories {
        mavenLocal()
        maven {
            url 'http://my-local-jfrog-artifactory.com:8081/artifactory/libs-release/'
            allowInsecureProtocol = true
        }

        maven {
            url 'http://my-local-jfrog-artifactory.com:8081/artifactory/libs-snapshot/'
            allowInsecureProtocol = true
        }
    }
}
```
NOTE: The server *my-local-jfrog-artifactory.com* is a *JFrog Artifactory OSS* and also acts as a mirror of *MavenCentral*.

As soon as I apply *launch4j* plugin in my *build.gradle*:
```
plugins {
   id 'java'
   id 'edu.sc.seis.launch4j' version '3.0.5'
}
```
Task *:compileJava* fails, as some of my locally hosted dependencies cannot be found:
```
> Task :my-app:compileJava FAILED
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':my-app:compileJava'.
> Could not resolve all files for configuration ':my-app:compileClasspath'.
   > Could not find com.example:my-locally-hosted-lib:1.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/example/my-locally-hosted-lib/1.0.0/my-locally-hosted-lib-1.0.0.pom
     Required by:
         project :my-app
...
```
So for me it looks like either *launch4j* plugin is ignoring my configured repositories or even does overwrite my repository configuration.
I guess latter one, as only location https://repo.maven.apache.org/maven2 is searched (which I did not configure at all).
Am I right or is there something wrong with my *gradle* build script?

My *Gradle* version: 8.5

**Comment by TheBoegl** [comment]
You guessed correctly as stated [here](https://github.com/TheBoegl/gradle-launch4j?tab=readme-ov-file#how-to-include), so please try to add your repositories in build.gradle as the `dependencyResolutionManagement.repositories` is an [incubating feature](https://docs.gradle.org/8.5/javadoc/org/gradle/api/initialization/resolve/DependencyResolutionManagement.html#getRepositories--) we currently do not support.

**Comment by janosch24** [comment]
Hi @TheBoegl,
thank you very much for your quick reply.
I tried the work-around you mentioned and added my repositories to *build.gradle*.
But I had to do it this way (as I don't use legacy build script notation):
```
plugins {
    id 'java-library'javafxplugin' version '0.1.0'
    id 'edu.sc.seis.launch4j' version '3.0.5' apply false
}

// == Configure the repos here ... ==
repositories {
    //  ...
}

// == Configuration to create a windows executable ... ==
apply plugin: 'edu.sc.seis.launch4j'
launch4j {
    // launch4j configuration goes here ...
}
```
Is this as you would expect?
Especially due to the *apply false* statement in the *plugins* section of the script it prevents me to use *launch4j-plugin* in a precompiled gradle convention plugin, as applying plugins is automatically done there (*apply false* ignored) ...
Nevertheless this work-around is ok for now.

Best regards,
Jan

**Comment by janosch24** [comment]
> You guessed correctly as stated [here](https://github.com/TheBoegl/gradle-launch4j?tab=readme-ov-file#how-to-include), so please try to add your repositories in build.gradle as the `dependencyResolutionManagement.repositories` is an [incubating feature](https://docs.gradle.org/8.5/javadoc/org/gradle/api/initialization/resolve/DependencyResolutionManagement.html#getRepositories--) we currently do not support.

Hi @TheBoegl,
thank you very much for your quick reply.
I tried the work-around you mentioned and added my repositories to *build.gradle*.
As far as I can see this works!

**Comment by TheBoegl** [comment]
Can we close this issue?

**Comment by janosch24** [comment]
Yes of course ...
Thanks again for your advice.
Very much appreciated!
