### ISSUE TITLE
Remove dependency for JavaPlugin

### ISSUE THREAD

**Issue by TheBoegl** [TheBoegl/gradle-launch4j#2]
Comment by David.42...@gmail.com (@david-hall)
>The snippet of build.gradle shown should also include a line saying "apply plugin: 'java'" since the java plugin is referenced as the default value of the jar property: >"lib/"+project.tasks[JavaPlugin.JAR_TASK_NAME].outputs.files.getSingleFile().name.
>
>I use launch4j (and this plugin) in a gradle sub-project which does not require the java plugin otherwise. The sub-project is simply for generating the Windows executable wrapper and a self extracting zip file with a bundled JRE. The main project is the one with all of the java code and the java plugin. Since the java plugin is included in the subproject, it creates a bunch of unnecessary jar files. Is there any way to make this plugin work without requiring the java plugin? Maybe keep the default as-is if the plugin is in the project, but otherwise default to an empty string? I think that approach would maintain backwards compatibility but would no longer cause the problems I describe in a project with no java compile tasks and therefore no java plugin needed.
>

Add missing Issue from google code.

**Comment by david-hall** [comment]
Thanks for making this change as well as the others I had requested. Thanks for publishing it on the public gradle plugins maven repo too. I have already incorporated version 1.1.0 into my project so I am now able to control the additional parameters through the plugin. This fix will be a big help by allowing me to remove the java plugin which is not otherwise needed in my sub project. Please let me know when the version in the public maven repo is updated so I can update the version in my project to utilize this fix.

**Comment by TheBoegl** [comment]
You're welcome.
The new version is up and running.

**Comment by david-hall** [comment]
I just tried version 1.1.1 and it looks like there's still some dependency not working. The only thing I changed from the working version of build.gradle is that the version of the launch4j plugin is changed to 1.1.1 instead of 1.1.0. Here's the error I got simply trying to run 'gradle tasks':

    An exception occurred applying plugin request [id: 'edu.sc.seis.launch4j', version: '1.1.1']
    > Task with name 'jar' not found in project ':platform:windows'.

**Comment by TheBoegl** [comment]
Oh, I've missed that, because my test subproject actually included the JavaPlugin through its parent... 
The new version is in the plugins repo.

**Comment by david-hall** [comment]
Version 1.1.2 seems to be working correctly. According to the "gradle dependencies" command my subproject is now fully independent of the java plugin. Thanks again for making this change.
