### ISSUE TITLE
NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver

### ISSUE THREAD

**Issue by rpomeroy** [TheBoegl/gradle-launch4j#21]
In attempting to create an executable for my spring-boot app I get the following:

 FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createExeWithJar'.
> Launch4J finished with non-zero exit value 1
Exception in thread "main" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver
  	at net.sf.launch4j.Main.main(Main.java:61)
  Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.io.HierarchicalStreamDriver
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	... 1 more

I added the XStream dependency to both the buildscript classpath and project classpath to no avail.  Here's my build.gradle

```groovy
buildscript {
    ext {
        springBootVersion = '1.3.0.RELEASE'
    }
    repositories {
        mavenCentral()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath('gradle.plugin.edu.sc.seis.gradle:launch4j:1.5.4')
        classpath('com.thoughtworks.xstream:xstream:1.4.8')
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot'
apply plugin: 'edu.sc.seis.launch4j'

launch4j {
    mainClassName = 'org.springframework.boot.loader.JarLauncher'
    icon = 'src/main/resources/ge.ico'
}



jar {
    baseName = 'cimnet-util'
    version = '1.0.0-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }
}


dependencies {
    compile('org.springframework.boot:spring-boot-devtools')
    compile('org.springframework.boot:spring-boot-starter-freemarker')
    compile('org.projectlombok:lombok')
    compile('net.sf.jopt-simple:jopt-simple:4.9')
    compile("com.beust:jcommander:1.48")
    compile('com.thoughtworks.xstream:xstream:1.4.8')
    testCompile('org.springframework.boot:spring-boot-starter-test') 
}

dependencyManagement {
	imports { 
		mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Brixton.M3" 
	}
}


eclipse {
    classpath {
         containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
         containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.9'
}

```

Any help is greatly appreciated

**Comment by TheBoegl** [comment]
On which OS are you building?

**Comment by TheBoegl** [comment]
BTW: please check if the same error occurs in version 2.5.5.

**Comment by rpomeroy** [comment]
Windows 7, Latest JDK. On vacation and away from my work laptop until the 30th. Can test when I get back.

**Comment by TheBoegl** [comment]
If you are on Win7 20aa6be and therefore version 1.5.5 won't help. I'll dick into this within the next week.
I've tagged the git version with the wrong number and I'm going to fix this.

**Comment by TheBoegl** [comment]
Your config (with spring=boot) results in the wrong xstream version 1.4.2 residing in `build/launch4j/bin/lib`. Ether I'll find the source for this or I'm going to call launch4j's main class directly and provide the classpath...
