### ISSUE TITLE
MissingMethodException: No signature of method: Launch4jPluginExtension.onSetCopyConfigurable()

### ISSUE THREAD

**Issue by enzanki-ars** [TheBoegl/gradle-launch4j#23]
```
groovy.lang.MissingMethodException: No signature of method: edu.sc.seis.launch4j.Launch4jPluginExtension.onSetCopyConfigurable() is applicable for argument types: (edu.sc.seis.launch4j.Launch4jPlugin$_apply_closure1$_closure39) values: [edu.sc.seis.launch4j.Launch4jPlugin$_apply_closure1$_closure39@64327959]
  Possible solutions: onSetCopyConfigurable(org.gradle.api.Action), getCopyConfigurable(), setCopyConfigurable(java.lang.Object)
```

**Comment by enzanki-ars** [comment]
Issue occurring on all builds: see https://circleci.com/gh/enzanki-ars/BotBattle/39 and https://github.com/enzanki-ars/BotBattle/blob/launch4j-test/build.gradle

**Comment by TheBoegl** [comment]
I've just cloned your repo but can't verify or reproduce your error. Could you please give more details about your build environment or - more appreciated - steps how to reproduce this.

**Comment by enzanki-ars** [comment]
Noticed the problem. My build script was using an old version of Gradle. It might be helpful to note somewhere the Gradle compatibility, though this was my fault as I intended to use 2.9.

**Comment by TheBoegl** [comment]
Just out of interest: Which gradle version did you use?

**Comment by enzanki-ars** [comment]
CircleCI was using 1.10. That explains everything. Will do some tests later, but Gradle most likely needs to 2.4+
