### ISSUE TITLE
Exposed tasks are replaced

### ISSUE THREAD

**Issue by Jazzepi** [TheBoegl/gradle-launch4j#24]
This Gradle plugin deletes and then reinstates several tasks.

http://stackoverflow.com/questions/34407151/gradle-task-does-not-execute-its-dependency/

This breaks a user modifying the available tasks during the normal configuration phase. I was able to get around it by using the afterEvaluate hook, but I think this is undesired behavior. The user shouldn't have to do strange things to successfully modify a task exposed by a plugin.

**Comment by aweigold** [comment]
@TheBoegl I have some ideas on how to fix this, as well as how to fix https://github.com/TheBoegl/gradle-launch4j/issues/7 after changing this.  Before I put in the work, are you taking contributions?

**Comment by TheBoegl** [comment]
@aweigold Of course I'll accept contributions.

**Comment by aweigold** [comment]
@TheBoegl Sounds great... I've worked around these two issues on my current project... I'll put together pull request(s) in the next month.

**Comment by TheBoegl** [comment]
@aweigold Did you have time for the PRs you talked about?

**Comment by aweigold** [comment]
@TheBoegl I haven't yet... a few other projects came up... but I was thinking about this the other day, I'll put it on my short list of things to do soon.  If you have other designs/direction in mind, don't wait on me.
