### ISSUE TITLE
EXE will not start the JVM

### ISSUE THREAD

**Issue by mhemmer** [TheBoegl/gradle-launch4j#25]
The exe will not start the jvm.

Using process monitor, the last error the process shows before exiting is this:

HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\GRE_Initialize\DisableMetaFiles 
This conversation is being saved. You'll see it soon in your Outlook Inbox folder.

it tries to open this key in the registry, and it isn't found

**Comment by mhemmer** [comment]
here is a csv of the process monitor

[Logfile.txt](https://github.com/TheBoegl/gradle-launch4j/files/116263/Logfile.txt)

**Comment by aweigold** [comment]
This is not an issue with this Gradle plugin, but likely an issue with your launch4j configuration.  I would recommend to find help on a launch4j forum or StackOverflow.

It may be helpful to run your executable with the "--l4j-debug" argument, as that will output some useful launch4j information for you.

**Comment by mhemmer** [comment]
It turns out that putting a mainClassName in there adds all the classpath with /lib on them.  It looks outside the .exe for a /lib directory of jars.   That should not happen.    I removed mainClassName and it all works now, because my oneJar specifies the mainClassName.
