### ISSUE TITLE
cleanCreateExe doesn't clean the UP-TO-DATE state

### ISSUE THREAD

**Issue by javydreamercsw** [TheBoegl/gradle-launch4j#29]
I'm trying to make sure the createExe is executed always so I'm trying something like this:

```
task copyToRoot(type: Copy, dependsOn: [cleanCreateExe, createExe]) {
   ....
    }

copyToRoot.mustRunAfter cleanCreateExe
copyToRoot.mustRunAfter createExe
```

It seems to do as expected, but still gives UP-TO-DATE result:

```
Executing: gradle :copyToRoot
Arguments: [-c, /home/javier/Desktop/pcgen/settings.gradle]

:cleanCreateExe UP-TO-DATE
:createExe UP-TO-DATE
...
```

Something seems off.

**Comment by javydreamercsw** [comment]
Looks like the task doesn't define it's output files so it's unable to clean them. But if this was the case it should execute every time and not skip.

**Comment by TheBoegl** [comment]
Though I don't understand why you'd like to create the exe every time, I'll gonna take a look into within the next few weeks.

**Comment by javydreamercsw** [comment]
Remove clutter. Is another build artifact like compiled code and jars that
shouldn't be captured in version control.

**Comment by TheBoegl** [comment]
Isn't it an option to ignore the compiled files?
