### ISSUE TITLE
Automatically install launch4j

### ISSUE THREAD

**Issue by sschuberth** [TheBoegl/gradle-launch4j#3]
It would be great if the plugin could automatically download and install (relative to the working tree) a given version of launch4j for use with the plugin.

**Comment by TheBoegl** [comment]
I'm looking into this.

**Comment by TheBoegl** [comment]
@sschuberth The current implementation attempt will by default download launch4j as plugin specific dependency to `project.buildDir/configuration.outputDir/bin` which usually corresponds to `build/launch4j/bin. Afterwards it will extract the auxiliary binaries for the current operating system and execute the launch4j.jar.
The missing documentation and integration into the master branch will follow, if this fulfills your expectations.

**Comment by sschuberth** [comment]
Sounds good to me, thanks for working on this! My main desire was to get rid of the need to manually download an install the launch4j dependency. WRT the internal implementation I'm mostly fine with anything that does the job :-)

**Comment by TheBoegl** [comment]
Could someone test if this works for OS X (version 10.8+)?

**Comment by sschuberth** [comment]
I've given version 1.2.0 a try on Mac OS X 10.10.4. When executing the `createExe` task the first time I get the message `launch4j: Application jar doesn't exist` and no `*.exe` file is being created. However, running the `createExe` task a second time yields in all tasks being "UP-TO-DATE", but still no `*.exe` file.

**Comment by sschuberth** [comment]
I just checked, that does not work on Windows for me either. Am I doing something stupid?

**Comment by sschuberth** [comment]
On the way to debug the cause of this I created https://github.com/TheBoegl/gradle-launch4j/pull/9, but that does not fully fix it either.

**Comment by sschuberth** [comment]
OK, second part of the problem indeed was that I did something stupid: I had the `launch4j {}` configuration block before the `application` plugin (which depends on the `java` plugin) was applied. With that fixed and my PR #9 merged it works on Windows.

On Mac, however, `createExe` now fails as it tries to start `windres`, which of course fails.

**Comment by sschuberth** [comment]
The latter issue is now fixed by PR #10.

**Comment by TheBoegl** [comment]
Thanks for the catch and your provided fixes!

**Comment by TheBoegl** [comment]
I missed to close this issue, though PR #10 fixed the latter issues. Please let me know if there are any issues left.
