### ISSUE TITLE
Please update to Launch4J 3.9.0

### ISSUE THREAD

**Issue by EmilyBjoerk** [TheBoegl/gradle-launch4j#30]
3.8 contains a bug that when the minimum JRE update version is set and the installed JRE version is > 100, will cause erroneously to report that the minimum version is not met. 

I.e. a min version set to 1.8.0_77  and actual JRE version of 1.8.0_101 will fail the minimum version check. 

This bug is resolved in 3.9.0. 

I reference the original bug report that I made to L4J tracker: https://sourceforge.net/p/launch4j/bugs/153/

**Comment by TheBoegl** [comment]
I'm going to fix this tomorrow.


Am 24.07.2016 um 22:59 schrieb Emily Björk:

**Comment by TheBoegl** [comment]
If an exception is thrown stating that _trademarks is not a field in VersionInfo_, try running `gradlew cleanLaunch4j`
