### ISSUE TITLE
Expose launch4j-generated outputs in `launch4j` task

### ISSUE THREAD

**Issue by alexanderfloh** [TheBoegl/gradle-launch4j#33]
I want to create a task that will copy the launch4j-generated outputs into a specific directory, e.g.

```
task deploy(type: Copy) {
  from launch4j
  into 'myoutputdir'
}
```

I've noticed that in [Launch4JPlugin](https://github.com/TheBoegl/gradle-launch4j/blob/develop/src/main/groovy/edu/sc/seis/launch4j/Launch4jPlugin.groovy#L80) you already connect the inputs and outputs for some of the tasks, but it is not propagated from the internal tasks to the user visible ones, please add that.

**Comment by TheBoegl** [comment]
Just for clarification: if you would create more executables with this plugin (see #7) would it be ok to retrieve them all as outputs.
At the moment if two executable are created under the same buildDir folder, the outputs would not differ.

**Comment by alexanderfloh** [comment]
I think that should be fine since you could only pull the one you need with the `CopySpec`'s `include`-/ `exclude`-patterns I guess.
