### ISSUE TITLE
Allow manual control of classpath configuration

### ISSUE THREAD

**Issue by alexanderfloh** [TheBoegl/gradle-launch4j#37]
I have a quite large project with multiple sub-modules where only some should end up as part of the application. For that I want to be able to control the classpath manually.

**Comment by TheBoegl** [comment]
I think this can be incorporated into the `copyConfigurable` with a change in [CreateXML](/TheBoegl/gradle-launch4j/blob/05cfb797d5ab8d64dc2bc446f973c7a3bfabffdc/src/main/groovy/edu/sc/seis/launch4j/CreateXML.groovy#L24)

**Comment by TheBoegl** [comment]
@alexanderfloh would the commit help?

**Comment by alexanderfloh** [comment]
@TheBoegl, thanks for the enhancement, I finally got around to give it a try.

Unfortunately I'm still unable to build my application, so I'll try to give more context.
As mentioned before, the application consists of multiple modules, and the distribution should look like this (items marked with a `*` should go in the classpath):
```
outputDir
| application.exe
+ \ module A
  + \ moduleA.jar *
    + \ lib (native .DLLs go here)
    + \ config *
    | <arbitrary other files>
+ \ module B
  + \ moduleB.jar *
    /* ... */
+ \ <third party libs> *
```

Ideally, I'd like to be able to convince the launch4j plugin to not make any assumptions about my directory structure. Just point it at a directory, specify what should be included in the classpath and have it generate an .exe-file.

Alternatively, being able to provide a `CopySpec` for copyConfigurable might work as well for me, but I'm a bit worried about that resulting in an unnecessary amount of copies of the output files.

Thanks for investing your time in this, I appreciate it.
