### ISSUE TITLE
Allow absolute path as output directory

### ISSUE THREAD

**Issue by alexanderfloh** [TheBoegl/gradle-launch4j#38]
When specifying an absolute path, the project build directory is prepended, resulting in an invalid path.

**Comment by TheBoegl** [comment]
If the plugin would allow an absolute output directory outside the `$buildDir` the 'clean' tasks will be messy/delete files you don't want to be deleted.

An option would be to keep the current setting and add add another task that syncs the output to your user defined folder.

**Comment by alexanderfloh** [comment]
Right, I haven't considered that.

Thanks!
