### ISSUE TITLE
Fails under new plugin architecture

### ISSUE THREAD

**Issue by byronpdx** [TheBoegl/gradle-launch4j#4]
I get an error of "`Error:(24, 0) Could not find property 'targetCompatibility' on root project ...`" when i use the new plugin architecture with launch4j. 

My file looks like 
```java
plugins {
    id 'java'
    id 'application'
    id 'edu.sc.seis.launch4j' version '1.1.2'
}
```

But it does work when I change it to
```java
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.edu.sc.seis.gradle:launch4j:1.1.2"
    }
}

apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'edu.sc.seis.launch4j'
```

This is not a big issue and I am not sure where the problem is, launch4j plugin, or in the new architecture. 

Thanks

**Comment by TheBoegl** [comment]
The reason for this seems to be, that the plugins feature does not set the targetCompatibility property for the java plugin explicitly.
