### ISSUE TITLE
Classpath

### ISSUE THREAD

**Issue by Tosken1337** [TheBoegl/gradle-launch4j#41]
Hi,

i have a question.
How is it possible to set the classpath.
The jar has no classpath configured in the manifest by dafeult.
How does launch4j handle the dependend jars?

Thanks

**Comment by TheBoegl** [comment]
If my memory serves me well the classpath is set in the executable. Check the log file after you run `path/to/executable --l4j-debug`.

**Comment by TheBoegl** [comment]
@Tosken1337 Do you need further help or can I close this question?

**Comment by Tosken1337** [comment]
Thank you very much. You can close this
