### ISSUE TITLE
Directory of the icon file

### ISSUE THREAD

**Issue by Tosken1337** [TheBoegl/gradle-launch4j#43]
I have the problem that the createExe task cannot find the icon.ico file specified.

```
launch4j {
    outputDir = "release"
    outfile = "App.exe"
    mainClassName = "com.something.AppStarter"
    opt = "-Djogamp.gluegen.UseTempJarCache=false"
    jreRuntimeBits = "32"
    libraryDir = "libs"
    icon = "icon.ico"
}
```

Commenting out the line works and it will create the exe under the folder ./build/release.
Placing the icon.ico in build or in the root doesn't work.

**Comment by Tosken1337** [comment]
Please delete question. Found out. My goofiness...

**Comment by TheBoegl** [comment]
This seems to be documented incorrectly.
