### ISSUE TITLE
Why "opt" property is a string

### ISSUE THREAD

**Issue by radistao** [TheBoegl/gradle-launch4j#46]
Most of the plugins with JVM wrapping (and not only JVM) use arguments as a list, but in this plugin it is just a string. Isn't it more conventional to make it as an array of strings?

**Comment by TheBoegl** [comment]
Sure, though I don't know why it is a string in the first place.
I'll try to make this change backwards compatible.

**Comment by radistao** [comment]
Thanks. What do you mean "the first place"? In launch4j xml config it is a multiple xml tag:
http://launch4j.sourceforge.net/docs.html

**Comment by TheBoegl** [comment]
Yes, but it seems @crotwell implemented it like launch4j's RcBuilder uses it [internally](/mirror/launch4j/blob/master/src/net/sf/launch4j/RcBuilder.java#L272):
```groovy
jre.opts.join(' ')
```
P.S.: I don't know how to link to this line in the [original repo](https://sourceforge.net/p/launch4j/git/ci/master/tree/src/net/sf/launch4j/RcBuilder.java).

**Comment by TheBoegl** [comment]
@radistao should 2d9d39d not suffice, please reopen this issue. Feel free to comment or improve this commit anyway.
Furthermore, expect a release containing this commit this week :smile: .

**Comment by radistao** [comment]
ok, i'll update the plugin as soon as you make a release and let you know the results. thanks a lot!
