### ISSUE TITLE
Setting an empty classpath and an executable JAR file

### ISSUE THREAD

**Issue by gravelld** [TheBoegl/gradle-launch4j#49]
In my setup I need launch4j to simply execute a JAR file which has a Main-Class setting in the manifest.

How how would one specify an empty classpath - so only the JAR specified in the jar parameter would be used to form the classpath? At the moment, all the dependencies for the Gradle project are listed in `$build/launch4j/lib` so I think those are also being added to the classpath.

I have tried:
```
copyConfigurable=false
```
And
```
copyConfigurable=[]
```
Neither seem to affect the lib/ folder.

Also, the generated `launch4j.xml` file is no longer stored in $build/launch4j - can that be retained for debugging purposes?

Now, maybe the listing of all libs in `$build/launch4j/lib` _doesn't_ mean the libs are all added to the classpath, but in the absence of the generated `launch4j.xml` file I don't have visibility of that.

Here are my wider settings:
```
launch4j {
	dontWrapJar=true 
	headerType="gui" 
	outfile="bliss.exe" 
	chdir="." 
	stayAlive=false
	copyConfigurable=false
	
	mainClassName='com.elsten.bliss.bootstrap.Bootstrap'
	jar="..\\lib\\com.elsten.bliss.bootstrap.jar"
	jreMinVersion='1.7.0'
	splashFileName="${projectDir}/src/dist/bin/bliss-splash.bmp"
	splashWaitForWindows=false 
	splashTimeout="5" 
	splashTimeoutError=false
	mutexName="bliss"
}
```

**Comment by TheBoegl** [comment]
@gravelld Are you sure that the resulting executable should locate your jar `com.elsten.bliss.bootstrap.jar` in its parent folders subfolder called lib?

In addition to that you should really take a look at the documentation and use the correct objects you assign to the properties.
I've fixed these issues:
```gradle
launch4j {
    dontWrapJar=true
    outfile="bliss.exe"

    //mainClassName='com.elsten.bliss.bootstrap.Bootstrap' // you do not need this if you do not wrap the jar
    jar="../lib/com.elsten.bliss.bootstrap.jar" // this is where the jar resides/is expected after you distribute it
    jreMinVersion='1.7.0'
    splashFileName="${projectDir}/src/dist/bin/bliss-splash.bmp"
    splashWaitForWindows=false
    splashTimeout=5
    splashTimeoutError=false
    mutexName="bliss"
}

jar {
    manifest {
        attributes 'Main-Class': 'com.elsten.bliss.bootstrap.Bootstrap'
    }
}
```

This results in the _correct_ execution of the jar.

**Comment by gravelld** [comment]
@TheBoegl Thanks for that. Yep, that's the location for the JAR. The parameters I have used above are from my original Ant build. I've been using Launch4j for many years.

    //mainClassName='com.elsten.bliss.bootstrap.Bootstrap' // you do not need this if you do not wrap the jar

I think I might have got mixed up; the Launch4j docs mark this as a required field: http://launch4j.sourceforge.net/docs.html . My previous build had to specify this; I'm also slightly changing the way classloading works in this version (did use OSGi, so the main class was the OSGi container).

I don't need the JAR definition - the JAR is built in a different project (this is a multi project build).

I think that has helped me realise I should be building this in a totally different build project, to avoid the runtime dependencies being brought into this project. 

I did that, and the exe works nicely. The classpath, as shown for `--l4j-debug-all`, just has the bootstrap JAR in it.

**Comment by gravelld** [comment]
So I'm wondering - is it something you want to support, classpath control, or should it just be down to the user to expect the project's dependencies be automatically chosen?

If that latter, this can be closed.

**Comment by TheBoegl** [comment]
Do you refer to the classpath control like in #48? If not please collaborate on your user case otherwise you can close this.

**Comment by gravelld** [comment]
I think so... basically I want a way of saying:

copyConfigurable=[]

And no classpath being generated, regardless of the dependencies of the containing project.

**Comment by gravelld** [comment]
Oh, btw, from the README.MD:

> The only required value is the mainClassName

https://github.com/TheBoegl/gradle-launch4j/blob/develop/README.md#configuration

**Comment by TheBoegl** [comment]
That is correct. In the special case of `dontWrapJar=true` it is up to the `jar` to be either runnable, i.e. having a `Main Class` defined in its manifest, or be called with `mainClassName`. Either option has a use case.
