### ISSUE TITLE
Targeted java version?

### ISSUE THREAD

**Issue by freystef** [TheBoegl/gradle-launch4j#5]
Hi,
I tried your launch4j gradle plugin, however the error message "Unsupported major.minor version 52.0" appears, that suggests that the plugin is compiled for Java 8. My machine is still on 7.
If it is the case, any specific reason for targeting 8?
Thanks,
Stefan Frey

**Comment by TheBoegl** [comment]
Actually this was not intended, though there are no public updates for JRE7 since April.

**Comment by freystef** [comment]
Thanks a lot! I am still on OpenJDK on my OpenSuse box.
