### ISSUE TITLE
How would i specify a cert to sign the exe?

### ISSUE THREAD

**Issue by dmodoomsirius** [TheBoegl/gradle-launch4j#50]
I was wondering what option i would use to specify a cert to sign a exe? Would i still sign it as a jar then it would extend to the exe?

I would appreciate any help.

**Comment by TheBoegl** [comment]
Have you tried to use sign4j?
I haven't found it on maven nor is it integrated in the current launch4j package.

**Comment by dmodoomsirius** [comment]
I have not. I will be looking into it right now.

**Comment by TheBoegl** [comment]
Another software would be [jsign](/ebourg/jsign), which you could call with a few modifications from the build script.
