### ISSUE TITLE
Error when specifying an absolute path for outputDir

### ISSUE THREAD

**Issue by laurre** [TheBoegl/gradle-launch4j#51]
I am unable to set an absolute path for the outputDir property. I get the following message:

> Could not normalize path for file 'C:\workspace\MyProj\build\C:\workspace\Other'.

Should this property work with an absolute path ? Or should this be better documented in the README ? In both cases, I can contribute with a PR.

**Comment by laurre** [comment]
Moreover, it is not clear to which folder this outputDir path is relative (it seems to be the 'build' folder).

**Comment by chadj2** [comment]
I think outFile is supposed to have the name of the exe with no path. The plugin will copy the resulting files and libraries to build/launch4j. You can use the distribution plugin to copy necessary files to an output location. 
You can have a look an an example here: [launch4j.gradle](https://github.com/chadj2/task-driver/blob/master/dist/launch4j.gradle)

**Comment by TheBoegl** [comment]
@laurre `outputDir` is relative to the project's `buildDir`. This way it is much easier to perform the clean up or internal tasks. As @chadj2 said, like build files from other plugins you can copy the result files afterwards where you want.
It would be helpful if you could contribute with PR.
