### ISSUE TITLE
Launch4j and Shadow plugins potentially don't play nice with each other

### ISSUE THREAD

**Issue by hotmeatballsoup** [TheBoegl/gradle-launch4j#55]
I have [the following project](https://github.com/hotmeatballsoup/gradle-launch4j-example) which uses this plugin as well as the [Shadow plugin](https://github.com/johnrengelman/).

The idea is simple:

1. Let the Shadow plugin produce a self-contained "fat" jar of all my classes and their transitive dependencies; then
2. Let this plugin wrap my shaded fat jar into an EXE

If you clone that project and run:

    ./gradlew clean build shadowJar createAllExecutables

You will get errors that I can't seem to fix. Any ideas (looking at the `build.gradle` file) as to how I can get this plugin to play nicely with my fat jar?

**Comment by TheBoegl** [comment]
@hotmeatballsoup If you want to see the console output in this test example, just add `headerType='console'` to the launch4j configuration, rebuild with `./gradlew createAllExecutables` and test it.

**Comment by hotmeatballsoup** [comment]
Thanks @TheBoegl but this is still not working for me. Check out my pushed changes which reflect your recommended changes. I changed my Gradle invocation to match your `./gradlew createAllExecutables --info` and this was the output:

```
Executing task ':createExe' (up-to-date check took 0.002 secs) due to:
  No history is available.
Starting process 'command 'java''. Working directory: /Users/zac.harvey/thelab/gradle-launch4j-example/build/launch4j Command: java -jar /Users/zac.harvey/thelab/gradle-launch4j-example/build/tmp/launch4j/bin-launch4j-3.9/launch4j-3.9.jar /Users/zac.harvey/thelab/gradle-launch4j-example/build/launch4j/createExe.xml
Successfully started process 'command 'java''
:createExe FAILED
:createExe (Thread[main,5,main]) completed. Took 0.771 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createExe'.
> Launch4J finished with non-zero exit value 1
  launch4j: Application jar doesn't exist.
```

Is there any configuration that I'm missing? Are you able to reproduce this at all? I'll note that I **don't** have a `launch4j.xml` file defined anywhere, as I assume I could just use defaults to start with. Thanks again for all your help thus far!

**Comment by TheBoegl** [comment]
You should have merged my PR...
Remove the jar property from the launch4j section, and do a clean run.

Just a tip: use .gitignore and don't commit generated temp files.

**Comment by hotmeatballsoup** [comment]
Thanks again, that worked!

So this produces a `zimbus.exe` file, which is clearly a native windows executable. In the docs I'm not seeing anything for producing native Mac OS executables, are Macs supported? Thanks again!

**Comment by TheBoegl** [comment]
You're welcome.

Launch4j only creates Windows binaries.
