### ISSUE TITLE
xmlConfigName doesnot seem to work

### ISSUE THREAD

**Issue by msuperdev** [TheBoegl/gradle-launch4j#57]
xmlConfigName does not work with either the launch4j plugin config or the External task. Is anyone trying to use the xml config and may be override some of the attributes with the plugin?

**Comment by TheBoegl** [comment]
What exactly are you trying to do?

**Comment by msuperdev** [comment]
I think I figured out what the issue is. 

First and foremost, there has been a code change between the version I have (2.3.0) and the develop branch. Second, the xml config is always regenerated no matter what, this is a problem. Tell me if there is a way to tell not to re-create the xml. I could be wrong here

**Comment by TheBoegl** [comment]
I really like to help you but I need more information to do that:
1. What version of this plugin are you using?
1. Which code change are you referring to?
There are a few changes but the only likely one is fa632f8. That did not change the internal handling of the 'per task xml file', but it is not responsible for not using your xml file.
1. Could you post a simplified example of your current project/issue?

**Comment by TheBoegl** [comment]
After rereading your issue again (and again): Do you want to _patch_ an existing launch4j xml file?
Neither it is possible with this implementation nor I'm planning to implement it.

**Comment by msuperdev** [comment]
I was trying to use a launch4j.xml with no classpath values. But everytime I ended up with libs in the build directory. With the debug parameter -Pl4j-debug, I could tell that the xml is generated everytime, even if the only property is xmlFileName. I will try to post a real example since you ask..

**Comment by msuperdev** [comment]
apply plugin: 'java'
apply plugin: 'edu.sc.seis.launch4j'

buildscript {
  repositories {
	jcenter()
  }
  dependencies {
	classpath 'edu.sc.seis.gradle:launch4j:2.3.0'
  }
}

repositories {
    jcenter()
}

dependencies {
    compile 'com.google.guava:guava:20.0'
    testCompile 'junit:junit:4.12'
}

launch4j {
  xmlFileName = "launch4j.xml"
}

---XML----
  <classPath>
    <mainClass>com.pkg.app.App</mainClass>
    <cp><just-one-jar-not-from-deps>.jar</cp>
  </classPath>

**Comment by TheBoegl** [comment]
This plugin uses the gradle style _convention over configuration_, hence, it configures many things for you. Take a look at [the documentation](https://github.com/TheBoegl/gradle-launch4j#how-to-configure) for the default values.

I don't get why you want to use the _almost empty_ but incorrect xml file, when this plugin already "wires" it's content correctly.

**Comment by msuperdev** [comment]
I am trying to generate the exe with a custom classpath (dependent jars exploded in various locations at runtime), and so do not want the plugin to modify this. The classpath also could not be configured in 2.3.0 through plugin configuration.

**Comment by TheBoegl** [comment]
The documentation I linked to is for the current snapshot version `2.4.0-1-SNAPSHOT`. The **classpath** property was added after `2.3.0`. Please try to use the snapshot version.

I could help you better if you give me more insight into your code base.

**Comment by msuperdev** [comment]
That's all the information I have. Just try to run createExe with no <cp> in classpath (no jars) for the xml. Just see what happens in build/launch4j/lib and tmp/createExe/launchj.xml

**Comment by msuperdev** [comment]
By the way, would this be enough
`buildscript {
  repositories {
    **jcenter()**
  }
  dependencies {
    classpath 'gradle.plugin.edu.sc.seis.gradle:launch4j:**2.4.0-1-SNAPSHOT**'
  }
}`

**Comment by TheBoegl** [comment]
Take a look at the (https://github.com/TheBoegl/gradle-launch4j#using-snapshot-versions)[documentation].

Running `createExe` on the following _build.gradle_ should result in your desired output, though IMHO your classpath is wrong:
```
buildscript {
  repositories {
    jcenter()
    maven { url "https://oss.jfrog.org/artifactory/oss-snapshot-local/" }
  }
  dependencies {
    classpath 'edu.sc.seis.gradle:launch4j:2.4.0-1-SNAPSHOT'
  }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'edu.sc.seis.launch4j'

repositories {
    jcenter()
}

dependencies {
    compile 'com.google.guava:guava:20.0'
    testCompile 'junit:junit:4.12'
}

launch4j {
  mainClassName = 'com.pkg.app.App'
  classpath = ['build/libs/l4jplugintest.jar']
}
```

**Comment by TheBoegl** [comment]
@msuperdev please take a look on the supported markup [here](https://guides.github.com/features/mastering-markdown/). I've fixed your markdown issues to at least read your source code...

**Comment by msuperdev** [comment]
Thanks for help. This can be closed now
