### ISSUE TITLE
<var></var> properties

### ISSUE THREAD

**Issue by henriIV** [TheBoegl/gradle-launch4j#59]
Is there a magical way that I am not aware of to set the var properties ?

    <var>blablaa=1</var>

So far I was only able to do so by modifying the source code

**Comment by TheBoegl** [comment]
It's not used anymore, is it?
Could you please hint where I could find the option in the latest launch4j 3.11 gui.

**Comment by henriIV** [comment]
It is in the "Set env.variables" tab Just between the JRE Tab and Splas tab
For each line you enter
a=12
b=23
You will end up with a var properties in the xml
\<var\>a=12\</var\>
\<var\>b=23\</var\>

**Comment by TheBoegl** [comment]
I missed that option... 😱 but will add it soon.

**Comment by TheBoegl** [comment]
@henriIV Please check version `2.4.0` and close this issue or comment here afterwards.

**Comment by henriIV** [comment]
The source code looks ok.  I will test it as soon as I resolve a little issue: I am unable to download some dependencies of your 2.4.0 version.  It seems that the batik jar is 404
404 - Path /org/apache/batik/com.springsource.org.apache.batik.ext.awt/1.7.0/com.springsource.org.apache.batik.ext.awt-1.7.0.jar not found in group repository "Public Releases Repositories (GA)" [id=public].  Any idea how to fix that ?

**Comment by TheBoegl** [comment]
Lets track the 404 issue in #60; Take a look at the "work around" there...

**Comment by henriIV** [comment]
Works perfectly. Thanks

I was able to resolve the 404 issue in the following way 
Instead of using the suggested buildscript on https://plugins.gradle.org/plugin/edu.sc.seis.launch4j  
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.edu.sc.seis.gradle:launch4j:2.4.0"
  }
}

I used 
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'edu.sc.seis.gradle:launch4j:2.4.0'
     }
}

Thank you
