### ISSUE TITLE
Windows reports virus

### ISSUE THREAD

**Issue by SergeVil** [TheBoegl/gradle-launch4j#63]
Hello,

I have created the exe file using gradle.plugin.edu.sc.seis.gradle:launch4j:2.4.2, but Windows 10 does not enable to run it.

What am I missing?

Thank you,
Serge

**Comment by TheBoegl** [comment]
This plugin utilizes launch4j, therefore, please report this issue to the launch4j developer at [sourceforge.net/p/launch4j/bugs/](https://sourceforge.net/p/launch4j/bugs/).

**Comment by SergeVil** [comment]
In one of the bugs the author proposes to sign the executable to avoid false positive by antivirus. Is it any way to do it in gradle?

**Comment by TheBoegl** [comment]
[Sign4j](https://sourceforge.net/p/launch4j/git/ci/master/tree/sign4j/) is not integrated in the maven artifact whereas I currently have no way to call it from this plugin, though you should try to sign your executable with it and test for AV false positives afterwards.
