### ISSUE TITLE
How to bund the jre?

### ISSUE THREAD

**Issue by yangwuan55** [TheBoegl/gradle-launch4j#64]
Please give me a sample code for gradle.
Thanks a lot!!!

**Comment by TheBoegl** [comment]
You can do it as simple as 
```
plugins {
  id 'java'
  id 'edu.sc.seis.launch4j' version '2.4.2'
}
launch4j {
  mainClassName = 'com.example.myapp.Start'
  icon = 'icons/myApp.ico'
  bundledJrePath = 'PATH_TO_YOUR_PROVIDED_JRE' \\ e.g '%ProgramFiles%/MyProject/jre'
  \\ more configuration options
}
```
Keep in mind that the created executable is 32-bit, therefore, keep in mind that `'%ProgramW6432%` exists, too.

**Comment by yangwuan55** [comment]
I set this,but can not work....
If correct setting,do jre will included to the exe?

**Comment by TheBoegl** [comment]
A bundled JRE will not get packed into the executable.

This plugin is more or less just a wrapper to access launch4j, therefore, take a thorough look at launch4j's [documentation](http://launch4j.sourceforge.net/docs.html).

**Comment by TheBoegl** [comment]
Closing this due to no response or further questions.

**Comment by yangwuan55** [comment]
I'm so sorry...
I had find the way.
