### ISSUE TITLE
Is there a way to suppress the lib folder alongside the .exe?

### ISSUE THREAD

**Issue by phillip-urioste** [TheBoegl/gradle-launch4j#68]
I'm using this plugin in conjunction with the shadowjar, and when I double-click the .exe after deleting the adjacent lib/ folder, my program runs just fine. It seems I don't need that folder.

**Comment by TheBoegl** [comment]
Currently that outcome is expected. Just distribute your shadowed jar or the launch4j wrapped exe.

**Comment by micheljung** [comment]
Too bad; this causes unnecessary file system operations and increases build size.

At least, I'm cleaning it up like this:
```
createExe {
  doLast {
    // https://github.com/TheBoegl/gradle-launch4j/issues/68
    delete("${buildDir}/${launch4j.outputDir}/${launch4j.libraryDir}")
  }
}
```

**Comment by TheBoegl** [comment]
Closing this again as 81d2570889 should have fixed this.
