### ISSUE TITLE
createExe task fails with icon file

### ISSUE THREAD

**Issue by osca** [TheBoegl/gradle-launch4j#69]
The task runs without an icon on OSX (10.13.2) and Debian Wheezy. But with an icon, it fails with following message:

:createExe FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createExe'.
> net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): .../build/tmp/launch4j/bin-launch4j-3.11/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /var/folders/58/wsb5xtzs6fggdqp0h7zxx21w0000gn/T/launch4j3925078529018637026rc /var/folders/58/wsb5xtzs6fggdqp0h7zxx21w0000gn/T/launch4j8772314785015631283o

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

Configuration:
```
launch4j {  
    mainClassName = 'ui.start.StartApplication'
    jar = "${project.tasks[JavaPlugin.JAR_TASK_NAME].archivePath}".replace(version + ".jar", "all-" + version + ".jar")
    productName = "jadda jadda" 
    internalName = "jaddajadda"
    icon = 'icons/windows/icon.ico'
    outfile = "jaddajadda_win_v${project.version}.exe"
    jreMinVersion = "1.8.0_20"
    initialHeapSize = 256
    maxHeapSize = 256
    jvmOptions = ["-Dfile.encoding=UTF8", "-Xmx256m", "-Xms256m"] 
}
```

I tried this with many various icon files. I'm using plugin version 2.4.2

**Comment by pdirksen** [comment]
+1

**Comment by juriritter** [comment]
+1

**Comment by TheBoegl** [comment]
Is your icon file really located in an icons folder located next to your executable?
The [documentation](/TheBoegl/gradle-launch4j#how-to-configure) states to use `A relative path from the outfile or an absolute path to the icon file`.
