### ISSUE TITLE
Multiple Executables

### ISSUE THREAD

**Issue by aaiezza** [TheBoegl/gradle-launch4j#7]
Love the plugin @TheBoegl! Seriously good work.

I did want to inquire about being able to create more than one executable. I know that gradle tasks cannot be run more than once, but my goal is to create tasks that essentially alter the launch4j settings and then run createExe. Of course it wouldn't be able to work like that.

Is there a way to do what I'm asking now and I'm ignorant to gradle's ability? If so disregard this, otherwise do you think this is a feature worth including?

Thanks

**Comment by TheBoegl** [comment]
Currently there is no method - I know of - to accomplish this.
I really like to see this feature happen, but I don't know how and when...

**Comment by TheBoegl** [comment]
If you have not found a way around this: create the multiple executables with the help of multiple gradle runs passing to each a different [argument ](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties)like `-Plaunch4j=firstChoice` and configure launch4j different for each 'parameter'. Afterwards you can just script a batch file or configure your IDE to call the launch4j task with different parameters.

**Comment by ravermeister** [comment]
would like to see that feature too :)

**Comment by TheBoegl** [comment]
@ravermeister have you tried my workaround from above?

**Comment by ravermeister** [comment]
To be honest, I stopped working on the actual gradle script cause it is already more than twice as big (and complex) as my ant script :) 

I have a Software with java and an Platform dependent part, so I build Versions for Linux/Windows for 32/64bit.  and for windows the executables too. in my Gradle Script I managed to create all of them within a Single build Task. I want to start from scratch and try to solve it with Separate "Projects" and one main Project which depends on them. I guess it is a better way than now. 

thanks for your help

**Comment by Nicklas2751** [comment]
I need this feature too. The workaround is no option for me cause i need various exes which will be included in a zip.

**Comment by wholladay** [comment]
I have the same use case as Nicklas2751. I need to create two exes with different launch4j settings and include them in a single zip file.

**Comment by TheBoegl** [comment]
@wholladay The workaround should work for you. Or you can wait a few days and test the new release.

**Comment by TheBoegl** [comment]
@wholladay, @Nicklas2751 and all: Would the current develop branch suffice your needs?
