### ISSUE TITLE
jreMinVersion is ignored

### ISSUE THREAD

**Issue by re3lex** [TheBoegl/gradle-launch4j#72]
I'm using jdk 1.10.0 in my IDE
looks like launch4j has an issue with supporting jdk more than 1.8.x

I'm trying to cheat launch4j by providing lower minVersion than I have.
My config:

```
launch4j {
    mainClassName = 'com.lex.competitorSiteParser.App'
    //icon = "${projectDir}/icons/myApp.ico"
    dontWrapJar = true
    bundledJre64Bit = true
     bundledJrePath = "jre"
    jreMinVersion = "1.8.0"
    jreMaxVersion = '1.10.0_999'
}
```

but createExe task is always failing with error: Invalid data: Minimum JRE version should be x.x.x[_xx] 
because generated xml file contains minVersion=1.10.0:
```
  <jre>
    <path>jre</path>
    <bundledJre64Bit>true</bundledJre64Bit>
    <bundledJreAsFallback>false</bundledJreAsFallback>
    <minVersion>1.10.0</minVersion>
    <maxVersion>1.10.0_999</maxVersion>
    <jdkPreference>preferJre</jdkPreference>
    <runtimeBits>64/32</runtimeBits>
  </jre>
```

Looks like plugin is ignoring provided _jreMinVersion_ value

**Comment by TheBoegl** [comment]
I'll look into this soon, though I'm not sure [if launch4j works](https://sourceforge.net/p/launch4j/feature-requests/107/) with Java 10.

**Comment by TheBoegl** [comment]
I can not reproduce this exact issue, though I opened [an upstream launch4j issue](https://sourceforge.net/p/launch4j/bugs/183/) because the minVersion and maxVersion should work with JRE9+.

If applicable you should only set the jreMinVersion and count on launch4j not working with jre 10 anyway.

**Comment by TheBoegl** [comment]
@re3lex the latest release _2.4.4_ should allow the JRE 9 and JRE 10 min or max versions, though your `<maxVersion>1.10.0_999</maxVersion>` will not be a valid version string. Use `<maxVersion>1.10.999</maxVersion>` instead.

**Comment by re3lex** [comment]
@TheBoegl cool! thanks a lot!
