### ISSUE TITLE
Understanding the bundled JRE behaviour

### ISSUE THREAD

**Issue by richardTingle** [TheBoegl/gradle-launch4j#75]
This is my current understanding of the bundledJrePath option. Is it correct?

- bundledJrePath is the relative path from the exe to the JRE, not where the JRE to be bundled currently is (i.e. not where launch4j should get it from to put where ever it wants)
- Where the bundled jre is not found it will just use the system JRE, not emit an error.
- Launch4j will not actually bundle the JRE, it is just being told where it is.
- As part of a separate dependant task we need to put the JRE _somewhere_ for Launch4j to pick it up

Assuming that's all correct where do we need to put the JRE and at what point in the build process

**Comment by TheBoegl** [comment]
The jre should be on the specified location on the end user's system.
Usually you'd place it there on the provision/installation step.

**Comment by richardTingle** [comment]
Ok, am I correct when i say "Where the bundled jre is not found it will just use the system JRE, not emit an error."

**Comment by TheBoegl** [comment]
Yes

**Comment by TheBoegl** [comment]
@richardTingle please close this if your questions are satisfactorily answered.

**Comment by richardTingle** [comment]
This may be beyond what the plugin would do and may be more about launch4j but my initial assumption was that the plugin/launch4j would bundle the jre whereever it wanted it (if told were it was in the source, I initially thought that was what  bundledJrePath was, a parameter for where the jre to be bundled was). If that can't be the case it may make sense to make it clear the docs that that isn't what's happening
