### ISSUE TITLE
Gives NoClassDefFoundError if dependencies is mentioned using implementation in gradle file

### ISSUE THREAD

**Issue by Shiva7071007** [TheBoegl/gradle-launch4j#78]
I have JAVA project myAPP and it depends on another project which is of library JAVA type myLibrary.
When I mention the dependencies using new method in myAPP build.gradle using 
"implementation project(':myLibrary')", 
the executable gives error NoClassDefFoundError :package.path.myLibrary.LibraryClass.

However, if i mention the dependencies using the old method:
"compile project(':myLibrary')"
the executable runs as expected without any error. 

Am I doing something wrong? or is it something with this library?

**Comment by Shiva7071007** [comment]
One thing that I also noticed that when I run "generate exe" task after doing simple build, it still fails while executing generated executable but if I do build needed first, it works.

**Comment by TheBoegl** [comment]
I don't really get what you are doing or wanting this plugin to do.
Could you please provide a small example that fails, thus I can clearly see the failing result.

**Comment by floating-cat** [comment]
I have a same problem, you can download a small example here:

**Comment by tomihawk** [comment]
I'd like to add my voice to this and see the plugin updated to include the new "implementation" keyword for runtime dependencies.  Both "compile" and "runtime" have been deprecated in Gradle 5.  See https://docs.gradle.org/current/userguide/java_library_plugin.html

> The compile configuration still exists but should not be used as it will not offer the guarantees that the api and implementation configurations provide.

Gradle init and the majority of the gradle documentation has been updated to use "implementation" without mentioning "compile" anywhere.
