### ISSUE TITLE
Please add support for setting 'chdir' property with an empty value:

### ISSUE THREAD

**Issue by evelak** [TheBoegl/gradle-launch4j#79]
After building exe directly with launch4j I can see from the --l4j-debug-all logs that the current working directory is not being overridden (Resurece 8 is <NULL>):

....
Resource 8:	<NULL>
....

After building exe with launch4j gradle plugin and having in the build.gradle:
createExe {
    ..
    chdir = ''
	..
}

I can see from the --l4j-debug-all logs that the current working directory is being overridden (Resource 8 is '.'):

...
Resource 8:	.
Working dir:	C:\directory\of\executable\.	
...

Feature is needed for profile cases, where working dir is not in relation with exe location (exe is installed in Program Files, but working dir is under user and different for each install/user).

**Comment by evelak** [comment]
Issue is still blocking development. Any news?

**Comment by TheBoegl** [comment]
If I find time this will get fixed first though PRs are welcomed anytime.

**Comment by evelak** [comment]
#81 Changed chdir truthfulness check to null check, since empty string in Groovy seems to be falsy, thus chdir falls to default value.  
Can you please review my pull request and on approval publish new plugin version?

**Comment by TheBoegl** [comment]
Thanks for your PR!
It is merged and published as version _2.4.5_.

**Comment by evelak** [comment]
Works perfectly. Thank you!
