### ISSUE TITLE
Use the x86 version of Launch4j for Mac OS X

### ISSUE THREAD

**Issue by Thunderforge** [TheBoegl/gradle-launch4j#8]
The main page of this project has a big warning about how Launch4j is written for PPC, which no longer works since OS 10.7 (Lion). In fact, Launch4j does have a version of x86 processors on OS X that is compatible with OS 10.7 and later. This can clearly be seen on the download page of [Launch4j 3.8](http://sourceforge.net/projects/launch4j/files/launch4j-3/3.8/), the latest version as of this writing. In fact, no PPC version is available any more.

Gradle-launch4j should use a version of Launch4j that supports x86 processors, and update its instructions accordingly.

**Comment by TheBoegl** [comment]
Thanks for that hint. I'll remove this section from the instructions.
