### ISSUE TITLE
Plugin adds jcenter repository definition to project using the plugin

### ISSUE THREAD

**Issue by wagnerma** [TheBoegl/gradle-launch4j#80]
In strict environments it is a problem, that the plugin adds the jcenter repository to project using this plugin.

10:30:19.760 [DEBUG] [org.gradle.api.Project] Adding the jcenter repository to retrieve the launch4j files.

The repository should only be added to the plugin resolution not to the project using this plugin.

**Comment by TheBoegl** [comment]
I haven't found another way to retrieve the launch4j library if no repository is available as far as I know there was no option to add a repository for just this dependency resolution. If there is please let me know.

How would you like to provide the launch4j dependencies in your environment?
The easiest solution would be for you to declare a file repository that contains launch4j and it's dependencies.
