### ISSUE TITLE
Can not unset jreMinVersion (to ignore system installed JRE/JDKs)

### ISSUE THREAD

**Issue by nikolauskrismer** [TheBoegl/gradle-launch4j#83]
According to the documentation of launch4j, there are three possibilities to use the path/jreMinVersion/jreMaxVersion properties:

From http://launch4j.sourceforge.net/docs.html:
* `<path>`
Run if bundled JRE and javaw.exe are present, otherwise stop with error.
* `<path> + <minVersion>  [+ <maxVersion>]`
Use bundled JRE first, if it cannot be located search for Java, if that fails display error message and open the Java download page.
* `<minVersion>  [+ <maxVersion>]`
Search for Java, if an appropriate version cannot be found display error message and open the Java download page.

However, with the plugin I can not get the first option (no minVersion and no maxVersion) to work.
If I set jreMinVersion = '' then it falls back to the targetCompatibility (same for jreMinVersion = null).

Is there another possibility to force the bundled jre/jdk to be used (not using any system installations)?

**Comment by TheBoegl** [comment]
@nikolauskrismer this should be fixed in _2.4.6_

**Comment by nikolauskrismer** [comment]
confirmed... just tested it with the new version.
When completely leaving out the jreMinVersion property, then solely a bundled jre is used...
