### ISSUE TITLE
OpenJDK 11 runtime

### ISSUE THREAD

**Issue by mdumont-arcom** [TheBoegl/gradle-launch4j#85]
Hi, 
I'm having a problem with the launch4j plugin.
When I run the executable using openJDK 11, an error message appears: "This application requires a Java Runtime Environment 11.0.0".
My JAVA_HOME variable: "C: \ development \ JDK \ jdk-11"
I can't find any solution.
How to correct the problem?

thank you

**Comment by TheBoegl** [comment]
This is related to [launch4j issue 197](https://sourceforge.net/p/launch4j/bugs/197/).

Take a look at the given [work-around in this comment](https://sourceforge.net/p/launch4j/bugs/197/#d574)

**Comment by Jazzepi** [comment]
Just to be clear Launch4j doesn't use JAVA_HOME to locate the JRE.

> Grzegorz Kowal - 2019-01-02
> JAVA_HOME is not used by launch4j. It either searches the registry or you
> need to specify the java directory as absolute or relative path (bundled
> JRE path).

**Comment by TheBoegl** [comment]
Last time I checked that was true.

**Comment by TheBoegl** [comment]
Closing this as the current plugin version provides at least launch4j 3.14, which works with java versions 9+.
