### ISSUE TITLE
Not finding bundled JDK

### ISSUE THREAD

**Issue by jpschewe** [TheBoegl/gradle-launch4j#87]
I've been using gradle-launch4j to create executables that rely on Java already being installed. Now I'm working to create an executable that depends on a bundled JDK.

I've downloaded the OpenJDK 12.0.2 zip file for Windows and uncompressed it next to the executable.

I've added the following lines to my gradle configuration.
```
createExe {
        ...
        bundledJrePath = "jdk-12.0.2"
        bundledJre64Bit = true
        bundledJreAsFallback = true
}
```

When I run with "--l4j-debug-all" I get an error that the JDK cannot be found. Looking in the resulting log file I see the following:

```
bundledJreSearch()
Resource 29:	<NULL>
Resource 1:	<NULL>
installedJreSearch()
```

This suggests to me that the bundled JDK isn't being specified in the executable. 

What have I configured incorrectly?

**Comment by TheBoegl** [comment]
Please take a look at [this launch4j feature request](https://sourceforge.net/p/launch4j/feature-requests/127) as this is an issue with launch4j itself not this wrapper...

**Comment by jpschewe** [comment]
No, I don't think that's the issue. I don't need to recognize the JAVA_HOME environment variable. I just want to bundle a JDK next my executable and have the executable use it. Even removing bundledJreAsFallback doesn't help.

**Comment by jpschewe** [comment]
I'm not sure what I changed, but now it's working.
