### ISSUE TITLE
Configuration to change name of the generated EXE file?

### ISSUE THREAD

**Issue by bitbythecron** [TheBoegl/gradle-launch4j#91]
This plugin seems to name the generated EXE according to the root project name by default (`${rootProject.name}.exe`).

In my Gradle build I specify a runtime command switch (e.g. `-Dspecifier=XYZ`) which then becomes available to `build.gradle` as a system property (e.g. `${System.properties.getProperty('specifier')}`).

I would like to configure this plugin to produce an EXE of the form:

```
${rootProject.name}-${System.properties.getProperty('specifier')}.exe
```

Hence if my root project name is `my-app` and I build the EXE via:

```
./gradlew clean build shadowJar createExe -Dspecifier=BETA
```

Then I would like this plugin to produce a `my-app-BETA.exe` file for me. **How can I do this?**

**Comment by IARI** [comment]
Have a look at [README.md#how-to-configure](https://github.com/TheBoegl/gradle-launch4j/blob/develop/README.md#how-to-configure)

String outfile | project.name+'.exe'
-- | --

So I if I understand it correctly, the config that achieves what you want should look like this:
(Note that I am using kotlin in gradle build scripts)

```kotlin
launch4j {
    outfile = "${project.name}-${System.properties.getProperty('specifier')}.exe"
}
```
