### ISSUE TITLE
launch4j and bouncycastle - This is a question not an issue

### ISSUE THREAD

**Issue by henriIV** [TheBoegl/gradle-launch4j#92]
It seems that making an .exe file is quite a challenge when using boucycastle jar files.
Does anyone have an idea how to do it ?

This is the best reference I have seen so far but I don't know if it works
https://stackoverflow.com/questions/39997888/maven-launch4j-plugin-how-to-configure-to-exclude-jars-used-by-the-exe

**Comment by TheBoegl** [comment]
Since I unfortunately have little time, please show us what you already got.
